# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waterfall.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Waterfall(object):
    def setupUi(self, Waterfall):
        Waterfall.setObjectName("Waterfall")
        Waterfall.resize(982, 580)
        self.gridLayout_2 = QtWidgets.QGridLayout(Waterfall)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_settings = QtWidgets.QGroupBox(Waterfall)
        self.plot_settings.setObjectName("plot_settings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.plot_settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bar_keys_and_event_markers = QtWidgets.QGroupBox(self.plot_settings)
        self.bar_keys_and_event_markers.setObjectName("bar_keys_and_event_markers")
        self.gridLayout = QtWidgets.QGridLayout(self.bar_keys_and_event_markers)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addWidget(self.bar_keys_and_event_markers, 0, 1, 1, 1)
        self.general_settings = QtWidgets.QGroupBox(self.plot_settings)
        self.general_settings.setObjectName("general_settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.general_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_title_layout = QtWidgets.QHBoxLayout()
        self.plot_title_layout.setObjectName("plot_title_layout")
        self.label = QtWidgets.QLabel(self.general_settings)
        self.label.setObjectName("label")
        self.plot_title_layout.addWidget(self.label)
        self.plot_title = QtWidgets.QLineEdit(self.general_settings)
        self.plot_title.setObjectName("plot_title")
        self.plot_title_layout.addWidget(self.plot_title)
        self.verticalLayout_2.addLayout(self.plot_title_layout)
        self.x_label_layout = QtWidgets.QHBoxLayout()
        self.x_label_layout.setObjectName("x_label_layout")
        self.label_2 = QtWidgets.QLabel(self.general_settings)
        self.label_2.setObjectName("label_2")
        self.x_label_layout.addWidget(self.label_2)
        self.x_label = QtWidgets.QLineEdit(self.general_settings)
        self.x_label.setObjectName("x_label")
        self.x_label_layout.addWidget(self.x_label)
        self.verticalLayout_2.addLayout(self.x_label_layout)
        self.y_label_layout = QtWidgets.QHBoxLayout()
        self.y_label_layout.setObjectName("y_label_layout")
        self.label_3 = QtWidgets.QLabel(self.general_settings)
        self.label_3.setObjectName("label_3")
        self.y_label_layout.addWidget(self.label_3)
        self.y_label = QtWidgets.QLineEdit(self.general_settings)
        self.y_label.setObjectName("y_label")
        self.y_label_layout.addWidget(self.y_label)
        self.verticalLayout_2.addLayout(self.y_label_layout)
        self.twenty_percent_line_layout = QtWidgets.QHBoxLayout()
        self.twenty_percent_line_layout.setObjectName("twenty_percent_line_layout")
        self.label_4 = QtWidgets.QLabel(self.general_settings)
        self.label_4.setObjectName("label_4")
        self.twenty_percent_line_layout.addWidget(self.label_4)
        self.twenty_percent_line = QtWidgets.QCheckBox(self.general_settings)
        self.twenty_percent_line.setText("")
        self.twenty_percent_line.setChecked(True)
        self.twenty_percent_line.setObjectName("twenty_percent_line")
        self.twenty_percent_line_layout.addWidget(self.twenty_percent_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.twenty_percent_line_layout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.twenty_percent_line_layout)
        self.thirty_percent_line_layout = QtWidgets.QHBoxLayout()
        self.thirty_percent_line_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.thirty_percent_line_layout.setObjectName("thirty_percent_line_layout")
        self.label_5 = QtWidgets.QLabel(self.general_settings)
        self.label_5.setObjectName("label_5")
        self.thirty_percent_line_layout.addWidget(self.label_5)
        self.thirty_percent_line = QtWidgets.QCheckBox(self.general_settings)
        self.thirty_percent_line.setText("")
        self.thirty_percent_line.setChecked(True)
        self.thirty_percent_line.setObjectName("thirty_percent_line")
        self.thirty_percent_line_layout.addWidget(self.thirty_percent_line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.thirty_percent_line_layout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.thirty_percent_line_layout)
        self.zero_percent_line_layout = QtWidgets.QHBoxLayout()
        self.zero_percent_line_layout.setObjectName("zero_percent_line_layout")
        self.label_6 = QtWidgets.QLabel(self.general_settings)
        self.label_6.setObjectName("label_6")
        self.zero_percent_line_layout.addWidget(self.label_6)
        self.zero_percent_line = QtWidgets.QCheckBox(self.general_settings)
        self.zero_percent_line.setText("")
        self.zero_percent_line.setChecked(True)
        self.zero_percent_line.setObjectName("zero_percent_line")
        self.zero_percent_line_layout.addWidget(self.zero_percent_line)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.zero_percent_line_layout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.zero_percent_line_layout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.general_settings)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.display_response_as_text = QtWidgets.QCheckBox(self.general_settings)
        self.display_response_as_text.setText("")
        self.display_response_as_text.setChecked(True)
        self.display_response_as_text.setObjectName("display_response_as_text")
        self.horizontalLayout_8.addWidget(self.display_response_as_text)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout_3.addWidget(self.general_settings, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.plot_settings, 0, 0, 1, 1)

        self.retranslateUi(Waterfall)
        QtCore.QMetaObject.connectSlotsByName(Waterfall)

    def retranslateUi(self, Waterfall):
        _translate = QtCore.QCoreApplication.translate
        Waterfall.setWindowTitle(_translate("Waterfall", "Dialog"))
        self.plot_settings.setTitle(_translate("Waterfall", "Waterfall Plot Settings"))
        self.bar_keys_and_event_markers.setTitle(_translate("Waterfall", "Bar Color Keys and Event Markers"))
        self.general_settings.setTitle(_translate("Waterfall", "General Settings"))
        self.label.setText(_translate("Waterfall", "Plot Title: "))
        self.label_2.setText(_translate("Waterfall", "X-Axis Label:"))
        self.label_3.setText(_translate("Waterfall", "Y-Axis Label: "))
        self.label_4.setText(_translate("Waterfall", "+20% Line:"))
        self.label_5.setText(_translate("Waterfall", "-30% Line:"))
        self.label_6.setText(_translate("Waterfall", "0% Line:"))
        self.label_7.setText(_translate("Waterfall", "Display patient response (CR,PR,PD,SD) as text above/below bar:"))

