# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waterfall.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Waterfall(object):
    def setupUi(self, Waterfall):
        Waterfall.setObjectName("Waterfall")
        Waterfall.resize(982, 580)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Waterfall)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_settings = QtWidgets.QGroupBox(Waterfall)
        self.plot_settings.setObjectName("plot_settings")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.plot_settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.plot_settings)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_title_layout = QtWidgets.QHBoxLayout()
        self.plot_title_layout.setObjectName("plot_title_layout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.plot_title_layout.addWidget(self.label)
        self.plot_title = QtWidgets.QLineEdit(self.tab)
        self.plot_title.setObjectName("plot_title")
        self.plot_title_layout.addWidget(self.plot_title)
        self.verticalLayout.addLayout(self.plot_title_layout)
        self.x_label_layout = QtWidgets.QHBoxLayout()
        self.x_label_layout.setObjectName("x_label_layout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.x_label_layout.addWidget(self.label_2)
        self.x_label = QtWidgets.QLineEdit(self.tab)
        self.x_label.setObjectName("x_label")
        self.x_label_layout.addWidget(self.x_label)
        self.verticalLayout.addLayout(self.x_label_layout)
        self.y_label_layout = QtWidgets.QHBoxLayout()
        self.y_label_layout.setObjectName("y_label_layout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.y_label_layout.addWidget(self.label_3)
        self.y_label = QtWidgets.QLineEdit(self.tab)
        self.y_label.setObjectName("y_label")
        self.y_label_layout.addWidget(self.y_label)
        self.verticalLayout.addLayout(self.y_label_layout)
        self.twenty_percent_line_layout = QtWidgets.QHBoxLayout()
        self.twenty_percent_line_layout.setObjectName("twenty_percent_line_layout")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.twenty_percent_line_layout.addWidget(self.label_4)
        self.twenty_percent_line = QtWidgets.QCheckBox(self.tab)
        self.twenty_percent_line.setText("")
        self.twenty_percent_line.setChecked(True)
        self.twenty_percent_line.setObjectName("twenty_percent_line")
        self.twenty_percent_line_layout.addWidget(self.twenty_percent_line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.twenty_percent_line_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.twenty_percent_line_layout)
        self.thirty_percent_line_layout = QtWidgets.QHBoxLayout()
        self.thirty_percent_line_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.thirty_percent_line_layout.setObjectName("thirty_percent_line_layout")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.thirty_percent_line_layout.addWidget(self.label_5)
        self.thirty_percent_line = QtWidgets.QCheckBox(self.tab)
        self.thirty_percent_line.setText("")
        self.thirty_percent_line.setChecked(True)
        self.thirty_percent_line.setObjectName("thirty_percent_line")
        self.thirty_percent_line_layout.addWidget(self.thirty_percent_line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.thirty_percent_line_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.thirty_percent_line_layout)
        self.zero_percent_line_layout = QtWidgets.QHBoxLayout()
        self.zero_percent_line_layout.setObjectName("zero_percent_line_layout")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.zero_percent_line_layout.addWidget(self.label_6)
        self.zero_percent_line = QtWidgets.QCheckBox(self.tab)
        self.zero_percent_line.setText("")
        self.zero_percent_line.setChecked(True)
        self.zero_percent_line.setObjectName("zero_percent_line")
        self.zero_percent_line_layout.addWidget(self.zero_percent_line)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.zero_percent_line_layout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.zero_percent_line_layout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.display_responses_as_text = QtWidgets.QCheckBox(self.tab)
        self.display_responses_as_text.setText("")
        self.display_responses_as_text.setChecked(True)
        self.display_responses_as_text.setObjectName("display_responses_as_text")
        self.horizontalLayout_8.addWidget(self.display_responses_as_text)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.btn_apply_general_settings = QtWidgets.QPushButton(self.tab)
        self.btn_apply_general_settings.setObjectName("btn_apply_general_settings")
        self.verticalLayout.addWidget(self.btn_apply_general_settings)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.data_viewer_container = QtWidgets.QVBoxLayout()
        self.data_viewer_container.setObjectName("data_viewer_container")
        self.horizontalLayout.addLayout(self.data_viewer_container)
        self.verticalLayout_2.addWidget(self.plot_settings)
        self.pushButton = QtWidgets.QPushButton(Waterfall)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Waterfall)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Waterfall)

    def retranslateUi(self, Waterfall):
        _translate = QtCore.QCoreApplication.translate
        Waterfall.setWindowTitle(_translate("Waterfall", "Dialog"))
        self.plot_settings.setTitle(_translate("Waterfall", "Waterfall Plot Settings"))
        self.label.setText(_translate("Waterfall", "Plot Title: "))
        self.label_2.setText(_translate("Waterfall", "X-Axis Label:"))
        self.label_3.setText(_translate("Waterfall", "Y-Axis Label: "))
        self.label_4.setText(_translate("Waterfall", "+20% Line:"))
        self.label_5.setText(_translate("Waterfall", "-30% Line:"))
        self.label_6.setText(_translate("Waterfall", "0% Line:"))
        self.label_7.setText(_translate("Waterfall", "Display patient response (CR,PR,PD,SD) as text:"))
        self.btn_apply_general_settings.setText(_translate("Waterfall", "Apply General Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Waterfall", "General settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Waterfall", "Color coding and markers"))
        self.pushButton.setText(_translate("Waterfall", "Finalize Plot for Export"))

